version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fakeMyKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - DEBUG=1
    volumes:
      - "./localstack:/var/lib/localstack"