spring:
  application:
    name: transaction-authorizer

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  data:
    dynamodb:
      endpoint: http://localhost:4566
      region: us-east-1
      access-key: fakeMyKeyId
      secret-key: fakeSecretAccessKey

  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
    timeout: 1500

lock:
  timeout:
    milliseconds: 15000
