spring:
  application:
    name: transaction-authorizer

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  data:
    dynamodb:
      endpoint: http://localhost:4566
      region: us-east-1
      access-key: fakeMyKeyId
      secret-key: fakeSecretAccessKey

  redis:
    host: localhost
    port: 6379
    timeout: 1500

lock:
  timeout:
    milliseconds: 15000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Transaction Authorizer API
    description: API for authorizing transactions
    version: v1.0.0
